2R - Copie/src/Entity/Ressource.php
<?php

namespace App\Entity;

use App\Repository\RessourceRepository;
use Doctrine\Common\Collections\ArrayCollection;
use Doctrine\Common\Collections\Collection;
use Doctrine\ORM\Mapping as ORM;

/**
 * @ORM\Entity(repositoryClass=RessourceRepository::class)
 */
class Ressource
{
    /**
     * @ORM\Id
     * @ORM\GeneratedValue
     * @ORM\Column(type="integer")
     */
    private $id;

    /**
     * @ORM\Column(type="string", length=255, nullable=true)
     */
    private $titre;

    /**
     * @ORM\Column(type="text", nullable=true)
     */
    private $resume;

    /**
     * @ORM\Column(type="date", nullable=true)
     */
    private $dateCrea;

    /**
     * @ORM\Column(type="boolean", nullable=true)
     */
    private $valide;

    /**
     * @ORM\Column(type="boolean", nullable=true)
     */
    private $exploite;

    /**
     * @ORM\Column(type="boolean", nullable=true)
     */
    private $demarre;

    /**
     * @ORM\ManyToOne(targetEntity=Utilisateur::class, inversedBy="ressources",cascade={"persist"})
     */
    private $Createur;

    /**
     * @ORM\OneToMany(targetEntity=Message::class, mappedBy="Ressource")
     */
    private $messages;

    /**
     * @ORM\OneToMany(targetEntity=Commentaire::class, mappedBy="ressource")
     */
    private $commentaires;

    /**
     * @ORM\OneToMany(targetEntity=File::class, mappedBy="ressource")
     */
    private $files;

    /**
     * @ORM\ManyToOne(targetEntity=Categorie::class, inversedBy="ressources")
     */
    private $categorie;

    /**
     * @ORM\ManyToOne(targetEntity=Etat::class, inversedBy="ressources")
     */
    private $etat;

    /**
     * @ORM\ManyToOne(targetEntity=Acces::class, inversedBy="ressources")
     */
    private $acces;

    /**
     * @ORM\OneToMany(targetEntity=Lien::class, mappedBy="ressource",cascade={"remove"})
     */
    private $utilisateurLie;

    /**
     * @ORM\OneToMany(targetEntity=Invitation::class, mappedBy="ressource")
     */
    private $invitations;

    /**
     * @ORM\Column(type="integer", nullable=true)
     */
    private $nbrConsultation;

    public function __construct()
    {
        $this->favoris = new ArrayCollection();
        $this->participants = new ArrayCollection();
        $this->messages = new ArrayCollection();
        $this->commentaires = new ArrayCollection();
        $this->files = new ArrayCollection();
        $this->utilisateurLie = new ArrayCollection();
        $this->dateCrea = new \DateTime('now');
        $this->invitations = new ArrayCollection();
        $this->nbrConsultation = 0;
    }


    public function getId(): ?int
    {
        return $this->id;
    }

    public function getTitre(): ?string
    {
        return $this->titre;
    }

    public function setTitre(?string $titre): self
    {
        $this->titre = $titre;

        return $this;
    }

    public function getResume(): ?string
    {
        return $this->resume;
    }

    public function setResume(?string $resume): self
    {
        $this->resume = $resume;

        return $this;
    }

    public function getDateCrea(): ?\DateTimeInterface
    {
        return $this->dateCrea;
    }

    public function setDateCrea(?\DateTimeInterface $dateCrea): self
    {
        $this->dateCrea = $dateCrea;

        return $this;
    }

    public function getValide(): ?bool
    {
        return $this->valide;
    }

    public function setValide(?bool $valide): self
    {
        $this->valide = $valide;

        return $this;
    }

    public function getExploite(): ?bool
    {
        return $this->exploite;
    }

    public function setExploite(?bool $exploite): self
    {
        $this->exploite = $exploite;

        return $this;
    }

    public function getDemarre(): ?bool
    {
        return $this->demarre;
    }

    public function setDemarre(?bool $demarre): self
    {
        $this->demarre = $demarre;

        return $this;
    }

    public function getCreateur(): ?Utilisateur
    {
        return $this->Createur;
    }

    public function setCreateur(?Utilisateur $Createur): self
    {
        $this->Createur = $Createur;

        return $this;
    }


    /**
     * @return Collection|Message[]
     */
    public function getMessages(): Collection
    {
        return $this->messages;
    }

    public function addMessage(Message $message): self
    {
        if (!$this->messages->contains($message)) {
            $this->messages[] = $message;
            $message->setRessource($this);
        }

        return $this;
    }

    public function removeMessage(Message $message): self
    {
        if ($this->messages->removeElement($message)) {
            // set the owning side to null (unless already changed)
            if ($message->getRessource() === $this) {
                $message->setRessource(null);
            }
        }

        return $this;
    }

    /**
     * @return Collection|Commentaire[]
     */
    public function getCommentaires(): Collection
    {
        return $this->commentaires;
    }

    public function addCommentaire(Commentaire $commentaire): self
    {
        if (!$this->commentaires->contains($commentaire)) {
            $this->commentaires[] = $commentaire;
            $commentaire->setRessource($this);
        }

        return $this;
    }

    public function removeCommentaire(Commentaire $commentaire): self
    {
        if ($this->commentaires->removeElement($commentaire)) {
            // set the owning side to null (unless already changed)
            if ($commentaire->getRessource() === $this) {
                $commentaire->setRessource(null);
            }
        }

        return $this;
    }

    /**
     * @return Collection|File[]
     */
    public function getFiles(): Collection
    {
        return $this->files;
    }

    public function addFile(File $file): self
    {
        if (!$this->files->contains($file)) {
            $this->files[] = $file;
            $file->setRessource($this);
        }

        return $this;
    }

    public function removeFile(File $file): self
    {
        if ($this->files->removeElement($file)) {
            // set the owning side to null (unless already changed)
            if ($file->getRessource() === $this) {
                $file->setRessource(null);
            }
        }

        return $this;
    }

    public function getCategorie(): ?Categorie
    {
        return $this->categorie;
    }

    public function setCategorie(?Categorie $categorie): self
    {
        $this->categorie = $categorie;

        return $this;
    }

    public function getEtat(): ?Etat
    {
        return $this->etat;
    }

    public function setEtat(?Etat $etat): self
    {
        $this->etat = $etat;

        return $this;
    }

    public function getAcces(): ?Acces
    {
        return $this->acces;
    }

    public function setAcces(?Acces $acces): self
    {
        $this->acces = $acces;

        return $this;
    }

    /**
     * @return Collection|Lien[]
     */
    public function getUtilisateurLie(): Collection
    {
        return $this->utilisateurLie;
    }

    public function addUtilisateurLie(Lien $utilisateurLie): self
    {
        if (!$this->utilisateurLie->contains($utilisateurLie)) {
            $this->utilisateurLie[] = $utilisateurLie;
            $utilisateurLie->setRessource($this);
        }

        return $this;
    }

    public function removeUtilisateurLie(Lien $utilisateurLie): self
    {
        if ($this->utilisateurLie->removeElement($utilisateurLie)) {
            // set the owning side to null (unless already changed)
            if ($utilisateurLie->getRessource() === $this) {
                $utilisateurLie->setRessource(null);
            }
        }

        return $this;
    }

    public function __toString()
    {
        return $this->getTitre();
    }

    /**
     * @return Collection|Invitation[]
     */
    public function getInvitations(): Collection
    {
        return $this->invitations;
    }

    public function addInvitation(Invitation $invitation): self
    {
        if (!$this->invitations->contains($invitation)) {
            $this->invitations[] = $invitation;
            $invitation->setRessource($this);
        }

        return $this;
    }

    public function removeInvitation(Invitation $invitation): self
    {
        if ($this->invitations->removeElement($invitation)) {
            // set the owning side to null (unless already changed)
            if ($invitation->getRessource() === $this) {
                $invitation->setRessource(null);
            }
        }

        return $this;
    }

    public function getNbrConsultation(): ?int
    {
        return $this->nbrConsultation;
    }

    public function setNbrConsultation(?int $nbrConsultation): self
    {
        $this->nbrConsultation = $nbrConsultation;

        return $this;
    }
}

2R - Copie/src/Form/RessourceType.php
<?php

namespace App\Form;

use App\Entity\Ressource;
use Symfony\Component\Form\AbstractType;
use Symfony\Component\Form\Extension\Core\Type\SubmitType;
use Symfony\Component\Form\FormBuilderInterface;
use Symfony\Component\OptionsResolver\OptionsResolver;

class RessourceType extends AbstractType
{
    public function buildForm(FormBuilderInterface $builder, array $options): void
    {
        $builder
            ->add('titre', null, [
                'label' => 'Titre',
                'translation_domain' => 'ressource' ,
                'required'=>true
            ])
            ->add('resume', null, [
                'label' => 'Resume',
                'translation_domain' => 'ressource' ,
                'required'=>true,
                'attr' => [
                    'style' => 'width:100%;margin-bottom:10%',
                ],
            ])
            ->add('dateCrea', null, [
                'label' => 'ressource.dateCrea',
                'translation_domain' => 'ressource'
            ])
            ->add('valide', null, [
                'label' => 'ressource.valide',
                'translation_domain' => 'ressource'
            ])
            ->add('exploite', null, [
                'label' => 'ressource.exploite',
                'translation_domain' => 'ressource'
            ])
            ->add('demarre', null, [
                'label' => 'ressource.demarre',
                'translation_domain' => 'ressource'
            ])
            ->add('Createur', null, [
                'label' => 'ressource.Createur',
                'translation_domain' => 'ressource'
            ])
            ->add('categorie', null, [
                'label' => 'Categorie',
                'translation_domain' => 'ressource' ,
                'required'=>true
            ])
            ->add('etat', null, [
                'label' => 'ressource.etat',
                'translation_domain' => 'ressource'
            ])
            ->add('acces', null, [
                'label' => 'ressource.acces',
                'translation_domain' => 'ressource'
            ])
            ->add('btn_fermer', SubmitType::class, [
                'label' => 'ressource.btn_fermer',
                'translation_domain' => 'ressource', 
                'label_html' => true,
                'attr' => [
                    'class' => 'btn btn-default',
                    'data-dismiss' => "modal",
                ]
            ])
            ->add('btn_valider', SubmitType::class, [
                'label' => 'ressource.btn_valider',
                'translation_domain' => 'ressource', 
                'label_html' => true,
                'attr' => [
                    'class' => 'btn btn-success',
                ]
            ])
        ;
    }

    public function configureOptions(OptionsResolver $resolver): void
    {
        $resolver->setDefaults([
            'data_class' => Ressource::class,
        ]);
    }
}

2R - Copie/src/Controller/RessourceController.php
<?php

namespace App\Controller;

use App\Entity\Ressource;
use App\Form\RessourceType;
use App\Repository\RessourceRepository;
use Symfony\Bundle\FrameworkBundle\Controller\AbstractController;
use Cnam\TwigBootstrapBundle\Table\DataTableQuery;
use Cnam\TwigBootstrapBundle\Table\DataTableResponse;
use Doctrine\ORM\EntityManagerInterface;
use Symfony\Contracts\Translation\TranslatorInterface;
use Sensio\Bundle\FrameworkExtraBundle\Configuration\ParamConverter;
use Symfony\Component\HttpFoundation\Request;
use Symfony\Component\HttpFoundation\Response;
use Symfony\Component\Routing\Annotation\Route;

/**
 * @Route("/ressource")
 */
class RessourceController extends AbstractController
{

    /** @var RessourceRepository */
    private $ressourceRepository;
    /** @var EntityManagerInterface */
    private $entityManager;
    /** @var TranslatorInterface */
    private $translator;

    public function __construct(RessourceRepository $ressourceRepository,
                                EntityManagerInterface $entityManager,
                                TranslatorInterface $translator)
    {
        $this->ressourceRepository = $ressourceRepository;
        $this->entityManager = $entityManager;
        $this->translator = $translator;
    }




    /**
     * @Route("/statConsultation", name="statConsultation", methods={"GET","POST"})
     */
    public function statConsultation(Request $request): Response
    {
        return $this->render('ressource/StatConsult.html.twig', [
            'ressources' => $this->ressourceRepository->findAll(),
        ]);
    }

    /**
     * @Route("/easterEgg", name="easterEgg")
     */
    public function easterEgg()
    {
        return $this->render('ressource/EasterEgg.html.twig', [
        ]);
    }

    /**
     * @Route("/statCreaExploit", name="statCreaExploit", methods={"GET","POST"})
     */
    public function statCreaExploit(Request $request): Response
    {
        return $this->render('ressource/StatCreaExploit.html.twig', [
            'ressources' => $this->ressourceRepository->findAll(),
        ]);
    }

    /**
     * @Route("/", name="ressource_index", methods={"GET","POST"})
     */
    public function index(Request $request): Response
    {
        $ressource = new Ressource();
        $form = $this->createForm(RessourceType::class, $ressource);
        $form->handleRequest($request);

        if ($form->isSubmitted() && $form->isValid()) {
            try {
                $this->entityManager->persist($ressource);
                $this->entityManager->flush();
            } catch (\Throwable $th) {
                $this->addFlash('error', $this->translator->trans('ressource.new.error',[],'ressource'));
                return $this->redirectToRoute('ressource_index');
            }
            $this->addFlash('success', $this->translator->trans('ressource.new.success',[],'ressource'));
            return $this->redirectToRoute('ressource_index');
        }

        return $this->render('ressource/index.html.twig', [
            'ressources' => $this->ressourceRepository->findAll(),
            'modal' => [
                'ressource' => $ressource,
                'form'  => $form->createView(),
                'title' => $this->translator->trans('ressource.new.boxtitle', [], 'ressource'),
                'requiredFields' => true,
            ]
        ]);
    }

    /**
     * @Route("/delete-ressource", name="delete_ressource", methods={"POST"})
     */
    public function delete(Request $request, RessourceRepository $ressourceRepository)
    {
        $ressource = $ressourceRepository->find(
            $request->get('delete_form_ressource')['id']
        );

        try {
            $this->entityManager->remove($ressource);
            $this->entityManager->flush();
        }
        catch (\Throwable $th) {
            $this->addFlash('error', $this->translator->trans('ressource.delete.error',[],'ressource'));
            return $this->redirectToRoute('ressource_index');
        }

        $this->addFlash('success', $this->translator->trans('ressource.delete.success',[],'ressource'));
        return $this->redirectToRoute('ressource_index');
    }

    /**
     * @Route("/{id}", name="ressource_show", methods={"GET","POST"})
     */
    public function show(Request $request, Ressource $ressource): Response
    {
        $form = $this->createForm(RessourceType::class, $ressource);
        $form->handleRequest($request);

        if ($form->isSubmitted() && $form->isValid()) {
            try {
                $this->entityManager->persist($ressource);
                $this->entityManager->flush();
            } catch (\Throwable $th) {
                $this->addFlash('error', $this->translator->trans('ressource.edit.error',[],'ressource'));
                return $this->redirectToRoute('ressource_index');
            }
            $this->addFlash('success', $this->translator->trans('ressource.edit.success',[],'ressource'));
            return $this->redirectToRoute('ressource_show',['id' => $ressource->getId()]);
        }

        return $this->render('ressource/show.html.twig', [
            'ressource' => $ressource,
            'modalEdit' => [
                'ressource' => $ressource,
                'form' => $form->createView(),
                'title' => $this->translator->trans('ressource.edit.boxtitle', [], 'ressource'),
                'requiredFields' => true,
            ],
        ]);
    }
}

2R - Copie/templates/ressource/OneRessource.html.twig
{% extends 'baseReseau.html.twig' %}

{% block stylesheets %}
    {{ parent() }}
    <link rel="stylesheet" href="{{ asset('style.css') }}" />
{% endblock %}

{% block searchbar %}

    <div class="search-bar">
        {{ form_start(search) }}
        <button class="right-side-button" @click="rightSide = !rightSide">
            <svg viewBox="0 0 24 24" width="24" height="24" stroke="currentColor" stroke-width="2" fill="none" stroke-linecap="round" stroke-linejoin="round" class="css-i6dzq1"><path d="M21 15a2 2 0 0 1-2 2H7l-4 4V5a2 2 0 0 1 2-2h14a2 2 0 0 1 2 2z"></path></svg>
        </button>
        {{ form_end(search) }}
    </div>

{% endblock %}

{% block content %}
    <title>{{ ressource.titre }}</title>

    <style>

        .wrap
        {
            margin:50px auto 0 auto;
            width:100%;
            display:flex;
            max-width:1200px;
            flex-wrap: wrap;
        }
        .tile
        {
            left: -80px;
            padding: 20px;
            width:75%;
            margin:15px;
            margin-bottom: 15px;
            background-color: #151728;
            display:inline-block;
            background-size:cover;
            position:relative;
            cursor:pointer;
            transition: all 0.4s ease-out;
            box-shadow: 0px 35px 77px -17px rgba(0,0,0,0.44);
            color:white;
            overflow: hidden;
            scrollbar-color: rgba(50,20,10,0.72) rgba(255,255,255,0.2);
            scrollbar-width: thin;
            scrollbar-radius: 5px;
        }
        .tile .text
        {
            width: 100%;
            position:absolute;
            padding:30px;
            height:calc(100% - 60px);
        }
        .tile h1
        {
            font-weight: 501;
            margin:0;
        }

        .tile p
        {
            font-weight:300;
            margin:20px 0 0 0;
            line-height: 25px;
        }

        .tile:hover
        {
            z-index: 2;
            overflow: auto;
            overflow-x: hidden;
            box-shadow: 0px 35px 77px -17px rgba(0,0,0,0.64);
            transform:scale(1.07);
        }

        .fichier
        {
            z-index: 11;
            position:absolute;
            bottom:20px;
            right:5px;
            margin: 0 auto;
            width:30px;
            height:30px;
            color:currentColor;
            display:flex;
            flex-direction:column;
            align-items:center;
            justify-content:space-around;
        }

        .fichier span
        {
            text-align: center;
            margin-top: 5px;
            background-color: white;
            border-radius: 10%;
            display:block;

        }

        .fichier span div
        {
            width: 0;
            height: 0;
        }

        .fichier span:hover div
        {
            width: min-content;
            height: min-content;
            margin-right: 5px;
            margin-left: 5px;
        }

        @media (max-width: 1000px) {
            .wrap {
                flex-direction: column;
                width:400px;
            }
        }
        .files{
            z-index: 10;
        }

        .login-box {
            z-index: 15;
            position: fixed;
            margin-top: 13%;
            left: 50%;
            width: 400px;
            padding: 0px 40px 40px 40px;
            transform: translate(-50%, -50%);
            background-color: rgba(127,90,131,0.7);
            background-image: linear-gradient(315deg, rgba(127,90,131,0.4) 0%, rgba(13,50,77,0.7) 74%);
            box-sizing: border-box;
            box-shadow: 0 15px 25px rgba(0,0,0,.6);
            border-radius: 10px;
        }

        .bouttonCrea{
            top: 0px;
            height: min-content;
            box-sizing: border-box;
            box-shadow: 0 15px 25px rgba(0,0,0,.6);
            border-radius: 10px;
            background-color: black;
            padding: 5px;
            margin-bottom: 13px;
        }
        a {
            text-decoration: none;
            color: white;
        }

        #commentaireForm{
            display: none;
        }

        .comm{
            border-radius: 10px;
            margin-top: 20px;
            padding: 5px;
            background-color: rgba(127,90,131,0.7);
            background-image: linear-gradient(315deg, rgba(127,90,131,0.4) 0%, rgba(13,50,77,0.7) 74%);
        }

        .Bouttons{
            display: flex;
            flex-direction: row;
            justify-content: space-evenly;
            width: 70%;
        }

        .bouttonComm{
            box-sizing: border-box;
            box-shadow: 0 15px 25px rgba(0,0,0,.6);
            border-radius: 10px;
            background-color: black;
            padding: 5px;
            margin-bottom: 13px;
            border: 1px solid rgba(60,141,188,1);
            transition:0.3s;
        }
        #InvitForm{
            display:none;
        }


    </style>

    <div class="row">
        <div class="col-md-12">
            {% block box_body %}

                <div class="wrap">


                    <div  id="commentaireForm">

                        {{ form_start(formComm) }}

                        {{ form_row(formComm.text) }}
                        <button class="bouttonCrea" type="submit">Envoyer</button>
                        {{ form_end(formComm) }}
                    </div>

                    <div class="login-box" id="InvitForm">
                        <button style="font-size: 30px" onclick=" document.getElementById('InvitForm').style.display = 'none';">
                            &times;
                        </button>
                        {{ form_start(formInvit) }}
                        <div class="user-box"> {{ form_row(formInvit.invite) }}</div>
                        <button class="bouttonCrea" type="submit">Envoyer</button>
                        {{ form_end(formInvit) }}
                    </div>

                    <div style="display: none" class="login-box" id="ChatForm">
                        <button  style="font-size: 40px" onclick=" document.getElementById('ChatForm').style.display = 'none';">
                            &times;
                        </button>
                        <div style="width: 100%;margin-bottom: 15%">
                        {% for message in ressource.messages  %}
                            <div style="display: flex;flex-direction: row">
                        <div style="font-size: 70%">{{ message.utilisateur }}</div> : {{ message }}</div>
                        {% endfor %}
                        </div>
                        {{ form_start(formChat) }}
                        <div class="user-box"> {{ form_row(formChat.text) }}</div>
                        <button class="bouttonCrea" type="submit">Envoyer</button>
                        {{ form_end(formChat) }}
                    </div>

                    <!-- .modal Refus Validation -->
                    <div style="display: none;"  id="MymodalRefus">
                        <div class="login-box">
                            <button style="font-size: 30px" onclick=" document.getElementById('MymodalRefus').style.display = 'none';">
                                &times;
                            </button>

                            {{ form_start(formCreate) }}


                            <h2>Ressource</h2>
                            <div class="user-box">
                                {{ form_row(formCreate.titre) }}
                            </div>
                            <div class="user-box">
                                {{ form_row(formCreate.resume) }}
                            </div>
                            <div class="user-box">
                                {{ form_row(formCreate.categorie) }}
                            </div>
                            <a href="#">
                                <span></span>
                                <span></span>
                                <span></span>
                                <span></span>
                                <button type="submit">Valider</button>
                            </a>
                            {{ form_end(formCreate) }}
                        </div>

                    </div>
                    <div class="Bouttons">
                    {%  if userCo is not empty %}
                        {% for lien in userCo.RessourceLiee %}

                            {% if lien.type == 'participe' and lien.ressource == ressource %}
                            <button class="bouttonCrea" onclick=" document.getElementById('InvitForm').style.display = 'block';">
                                Inviter des participants
                            </button>

                                <button class="bouttonCrea" onclick=" document.getElementById('ChatForm').style.display = 'block';">
                                    Chatter !
                                </button>
                            {% endif %}

                        {% endfor %}




                    {% if userCo.id == ressource.createur.id %}

                        <button class="bouttonCrea" onclick=" document.getElementById('MymodalRefus').style.display = 'block';">
                            Mofifier la ressource
                        </button>

                        {% if ressource.exploite == false %}
                            <a class="bouttonCrea" href="/exploiter/{{ ressource.id }}">Exploiter</a>
                        {% else%}
                            <a class="bouttonCrea" href="/exploiterNo/{{ ressource.id }}">Non Exploiter</a>
                        {% endif %}

                        {% if ressource.categorie.libelle == 'Activité' and ressource.demarre == false %}
                            <a class="bouttonCrea" href="/demarre/{{ ressource.id }}">Demarrer</a>
                        {% endif %}

                    <a class="bouttonCrea" href="/DeleteRessource/{{ ressource.id }}">Supprimer la ressource </a>

                    {% endif %}

                        <a class="bouttonCrea" href="/FavRessource/{{ ressource.id }}">Favoris</a>

                    {% endif %}
                </div>
                        <div class="tile">

                                    <h1 style="font-size: 50px;">{{ ressource.titre }}</h1> <br>
                            <div style="margin-left: 45px;">
                                    <h4>Resume :  {{ ressource.resume }}</h4> <br>
                                    <h4>Catégorie :  {{ ressource.categorie }}</h4> <br>
                                    <h4>Date de création :  {{ ressource.dateCrea ? ressource.dateCrea|date('Y-m-d') : '' }}</h4> <br>
                                    <h4>Valide :  {{ ressource.valide ? 'Yes' : 'No' }}</h4> <br>
                                    <h4>Exploité :  {{ ressource.exploite ? 'Yes' : 'No' }}</h4> <br>
                                    <h4>démarré :  {{ ressource.demarre ? 'Yes' : 'No' }}</h4> <br>

                                <h4><a class="bouttonComm">Commenter</a></h4>
                                <h4 class="comm">

                                    {% for commentaire in ressource.commentaires %}
                                        <div style="font-size: 80%">{{  commentaire.utilisateur}} </div>  {{ commentaire }}
                                        {% if userCo is not empty %}
                                        {% if commentaire.utilisateur ==userCo or userCo.droit == 'moderateur' %}
                                        <a style="font-size: 150%" href="\DeleteComm\{{ commentaire.id }}">&times;</a>
                                        {% endif %}
                                        {% endif %}
                                        <br>
                                        <br>
                                    {% endfor %}
                                </h4>
                            </div>
                        </div>
                </div>

                <script> const BouttonComms = document.querySelectorAll('.bouttonComm');
                    const commentaireForm = document.querySelector('#commentaireForm');

                    BouttonComms.forEach(function(BouttonComm){
                        BouttonComm.addEventListener('click', function(){
                            commentaireForm.parentNode.removeChild(commentaireForm);
                            BouttonComm.parentNode.appendChild(commentaireForm);
                            commentaireForm.style.display = 'block';
                        })
                    });</script>

            {% endblock %}
            {% block box_footer %}
            {% endblock %}
        </div>
    </div>
{% endblock %}